// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7sjTBjRLJA9pWeoZ07uZiu9y7iOSU-q8',
    appId: '1:942950500031:web:7c05adf25065f03920e80a',
    messagingSenderId: '942950500031',
    projectId: 'examgest-a96f9',
    authDomain: 'examgest-a96f9.firebaseapp.com',
    storageBucket: 'examgest-a96f9.firebasestorage.app',
    measurementId: 'G-Z93MPGH83K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgqYXEtCNULr95XkjOb4PAquuDjso_xc8',
    appId: '1:942950500031:android:882260a562496c5a20e80a',
    messagingSenderId: '942950500031',
    projectId: 'examgest-a96f9',
    storageBucket: 'examgest-a96f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzkChvew47z3aG6P8h_dSsuCDTU8IrUJo',
    appId: '1:942950500031:ios:a7abf6a61aea32d520e80a',
    messagingSenderId: '942950500031',
    projectId: 'examgest-a96f9',
    storageBucket: 'examgest-a96f9.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzkChvew47z3aG6P8h_dSsuCDTU8IrUJo',
    appId: '1:942950500031:ios:a7abf6a61aea32d520e80a',
    messagingSenderId: '942950500031',
    projectId: 'examgest-a96f9',
    storageBucket: 'examgest-a96f9.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7sjTBjRLJA9pWeoZ07uZiu9y7iOSU-q8',
    appId: '1:942950500031:web:8923557d9b49e32820e80a',
    messagingSenderId: '942950500031',
    projectId: 'examgest-a96f9',
    authDomain: 'examgest-a96f9.firebaseapp.com',
    storageBucket: 'examgest-a96f9.firebasestorage.app',
    measurementId: 'G-3Z3EQ1K8F1',
  );
}
